# Generated by Django 2.2.17 on 2020-12-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201130_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='atendente',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='assunto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contatar',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nome',
        ),
    ]
