# Generated by Django 2.2.17 on 2020-12-01 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201130_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='atendente',
        ),
    ]
