# Generated by Django 2.2.17 on 2020-12-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201130_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='assunto',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nome',
            new_name='title',
        ),
    ]
