# Generated by Django 2.2.17 on 2020-12-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201130_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='horario',
        ),
    ]
