# Generated by Django 2.2.17 on 2020-12-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201130_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='horario',
            new_name='created_date',
        ),
    ]
