# Generated by Django 2.2.17 on 2020-12-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201130_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nome',
            field=models.CharField(default='bola', max_length=200),
            preserve_default=False,
        ),
    ]
