# Generated by Django 2.2.17 on 2020-12-01 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201130_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
