# Generated by Django 2.2.17 on 2020-12-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
